### ISSUE TITLE
[Design]  profile management 스크롤뷰 수정

### ISSUE THREAD

**Issue by jklom0326** [APPSCHOOL2-Android/FinalProject-ShoppingMallService-team4#127]
### 목표

profile management 스크롤뷰 수정

### 체크리스트

- [x] profile management 스크롤뷰 수정
- [x] 혜택 정보 checkbox margin bottom 수정

**Comment by hxeyexn** [comment]
- 태그 및 라벨 잘못되어 fix -> design으로 수정

**Comment by hxeyexn** [comment]
- 수정한 fragment명 잘못되어 수정 (customoptionfragment ->  profile management)
