### ISSUE TITLE
[Feat] 상품 등록 데이터 전달 기능 구현

### ISSUE THREAD

**Issue by hxeyexn** [APPSCHOOL2-Android/FinalProject-ShoppingMallService-team4#176]
### 목표

상품 등록 데이터 전달 기능 구현

### 체크리스트

- [x] 상품 등록 화면에서 상품 상세 미리보기 화면으로 데이터 전달 (승현님)
- [x] 넘어온 데이터 상품 상세 미리보기 화면에 뿌려주기 (혜연)

**Comment by SeungHyeon-Hong** [comment]
이슈: 상품 등록 화면에서 미리보기 화면으로 이동 후, back으로 돌아왔을 경우
UI초기화X
하단 버튼 활성화 되지 않음.

**Comment by SeungHyeon-Hong** [comment]
초기화 이슈 수정함
