### ISSUE TITLE
[Refactor] User Essential 파일 수정

### ISSUE THREAD

**Issue by hxeyexn** [APPSCHOOL2-Android/FinalProject-ShoppingMallService-team4#190]
### 목표

User Essential 파일 수정
-> model 분리(#188)로 인해 수정 필요 

### 체크리스트

- [x] UserEssential 파일 이름 Essential로 변경
- [x] 불필요한 변수 삭제
- [x] Companion Object 내에 lateinit var db: FirebaseFirestore 관련 의논 (전체)
- [x] User Essential 수정으로 인한 SellerNotificationSettingFragment 오류 수정 @SeungHyeon-Hong

**Comment by hxeyexn** [comment]
@SeungHyeon-Hong  

User Essential 파일 수정으로 인해 발생한 SellerNotificationSettingFragment 오류 해결 부탁드려요~
190번 브랜치에서 수정하시면 됩니다!

**Comment by SeungHyeon-Hong** [comment]
UserModel, BuyerModel, SellerModel은 object 클래스로 변경함 -> 싱글톤

**Comment by SeungHyeon-Hong** [comment]
- Essential.kt 삭제
- fun getMilliSec() 만 MainActivity.kt로 옮김

**Comment by SeungHyeon-Hong** [comment]
@hxeyexn 

ProductDetailPreviewFragment 파일 참조 에러 수정 부탁드립니다~
이전까지의 작업은 190 브랜치에 커밋 올렸습니다.
